os:
  - linux
  - windows
  - osx

language: node_js
node_js:
- node

after_success:
  - node deploy.js success $WEBHOOK_URL
  
after_failure:
- node deploy.js failure $WEBHOOK_URL

branches:
  only:
  - master